Jenkinsfile

fix: Jenkins에서 테스트 빌드 제외

---

Dockerfile
Jenkinsfile

dockerfile 이미지 jdk -> jre 로 변경
jenkins 시작 시 시작됐다고 슬랙 알림 추가
- dockerfile : FROM openjdk:21-jdk-slim ---> FROM chainguard/jre:latest

fix:dockerfile and jenkinsfile

---

Jenkinsfile

기존 latest태그 --> "weasel-backend-${env.BUILD_NUMBER}"로 변경

fix: jenkinsfile tag 수정

---

Jenkinsfile

1. Main Branch 변경 감지
2. Web-hook을 통한 Jenkins Build Pipeline 동작
3. 현재 빌드번호를 갖는 docker image 생성 후 ECR에 Push
4. Kubernetes Deployment manifest파일의 이미지 최신화
5. ArgoCD가 Manifest파일 변경을 감지 후 서버에 적용

ci: update docker image version using ssh

---

Jenkinsfile

ci: change ImageURL

---

Jenkinsfile

- 이미지를 빌드할 때 이미지 명과 태그를 ecr에 바로 push할 수 있도록 변경
- 이미지 삭제하는 로직 변경

ci: ci pipeline enhancement

---

app/src/main/java/exam/master/api/HistoryApiController.java
app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/java/exam/master/dto/HistoryDTO.java
app/src/main/java/exam/master/dto/MemberDTO.java
app/src/main/java/exam/master/dto/PromptDTO.java
app/src/main/java/exam/master/repository/HistoryRepository.java
app/src/main/java/exam/master/repository/PromptRepository.java
app/src/main/java/exam/master/service/HistoryService.java
app/src/main/java/exam/master/service/MemberService.java
app/src/main/java/exam/master/service/PromptService.java
app/src/test/java/exam/master/service/MemberServiceTest.java
app/src/test/java/exam/master/service/PromptServiceTest.java

변경사항에 대한 설명
- HistoryApiController 생성
- PromptApiController 생성
1. Prompt등록(HistoryId가 있을 때)
2. Prompt등록(HistoryId가 없을 때)
3. Prompt리스트
4. History삭제(Prompt같이 삭제 확인)
- 관련 이슈 #23
- 아직 프론트 팀과 연동이 되지 않아 포스트맨으로 테스트 실행해야 합니다.

feat: History, Prompt 컨트롤러 생성

---

app/build.gradle
app/src/main/java/exam/master/api/HistoryApiController.java
app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/java/exam/master/config/S3Config.java
app/src/main/java/exam/master/service/AwsS3Service.java
app/src/main/java/exam/master/service/PromptService.java
app/src/main/resources/application.yml
app/src/test/resources/application.yml

설명 새로운 DB에서 프롬프트를 등록해야하는데 member controller와 병합 전

 member 회원가입 test

---

app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/resources/application.yml

변경사항에 대한 설명
- application.yml 파일 수정
1. 서버와 로컬에서 잘 돌아가는지 확인
2. 로컬에서 확인 하려면 aws configure 설정 필수

refactor: optional 옵션 추가

---

.gitignore
app/build.gradle
app/src/main/java/exam/master/api/HistoryApiController.java
app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/java/exam/master/config/InvokeModel.java
app/src/main/java/exam/master/service/PromptService.java
app/src/test/resources/application.yml

변경사항에 대한 설명
- bedrock 연동
- addPrompt 메소드에서 title 길이에 대한 버그 수정
- 관련 이슈 #34 
- 관련 이슈 #26

feat: bedrock 연동, addPrompt() 수정

---

app/build.gradle
app/src/main/java/exam/master/api/HistoryApiController.java
app/src/main/java/exam/master/api/MemberApiController.java
app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/java/exam/master/dto/LogInRequest.java
app/src/main/java/exam/master/dto/LoginResponse.java
app/src/main/java/exam/master/repository/MemberRepository.java
app/src/main/java/exam/master/service/MemberService.java
app/src/main/java/exam/master/service/PromptService.java
app/src/main/java/exam/master/session/SessionConst.java

변경사항에 대한 설명
- MemberApiController와 병합
- 프롬프트 등록과 히스토리 삭제할 때 테스트 멤버가 아닌 로그인 유저 멤버로 변경
1. PromptApiController.java 49번 라인 확인
2. HistoryApiController.java 32번 라인 확인
- 관련 이슈 #36

refactor: 컨트롤러에서 loginMember으로 네이밍 변경

---

app/src/main/java/exam/master/service/MemberService.java

회원가입시 프로필 파일 안줄 시 예외처리
- 변경 사항 1
- 변경 사항 2
- 변경 사항 3
1. example
- 관련 이슈 #1
- 관련 이슈 #2
- example

fix : 회원가입시 프로필 사진 안줬을 때 예외 처리

---

.idea/compiler.xml
.idea/modules.xml
.idea/modules/app/exam-master.app.main.iml
app/src/main/java/exam/master/api/MemberApiController.java

Session에서 Id를 가져와 사용 + 로그아웃할때만 request.getSession(false)로 세션 제어
- view, update, delete할 때 session에서 id를 찾아 사용
- login시 메서드 인자로 HttpSession 파라미터 전달 -> request.getSession 중복 제거
MemberApiController.java 확인
테스트해보고 에러 계속 발생 시 커밋 되돌릴 수 있음

fix: use Id from Session

---

app/src/main/java/exam/master/api/MemberApiController.java

session.getAttribute 반환값 확인 코드 추가
if (member == null) 조건 추가
- member/view 에 한개 추가

test: member 유효성 검사 테스트 코드

---

app/src/main/java/exam/master/api/MemberApiController.java

credential allow 코드 추가
- @CrossOrigin(
origins = "*",
allowCredentials = "true") // 쿠키 포함 허용
- MemberApiController.java 확인

fix: CORS credential allow 코드 추가

---

app/src/main/java/exam/master/api/MemberApiController.java

fix: 이전 credential 변경사항 초기화

---

app/src/main/java/exam/master/api/MemberApiController.java
app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/java/exam/master/dto/JoinResponse.java
app/src/main/java/exam/master/service/MemberService.java
app/src/main/resources/application.yml

회원가입 성공 여부
- 성공 여부와 회원 정보 일부를 리턴
1. 이미 등록된 회원으로 다시 회원가입 시도
- 관련 이슈 #50

fix: 회원가입 시 회원가입 성공 여부 확인

---

app/src/main/java/exam/master/api/HistoryApiController.java
app/src/main/java/exam/master/api/MemberApiController.java
app/src/main/java/exam/master/api/PromptApiController.java

변경사항에 대한 설명
- allowCredentials test

test: allowCredentials test

---

app/src/main/java/exam/master/api/HistoryApiController.java
app/src/main/java/exam/master/api/MemberApiController.java
app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/java/exam/master/service/MemberService.java
app/src/main/java/exam/master/service/PromptService.java

@CrossOrigin(origins = {"https://weasel.kkamji.net", "http://localhost:5173"}, allowCredentials = "true")
- 컨트롤러에 @CrossOrigin 확인
1. 프론트엔드 서버에서 벡엔드 서버로 요청을 할 때 쿠키를 같이 보내줘야 한다

refactor: cors 설정 수정

---

app/src/main/java/exam/master/api/PromptApiController.java
app/src/main/java/exam/master/config/InvokeModel.java
app/src/main/java/exam/master/domain/Prompt.java
app/src/main/java/exam/master/service/PromptService.java

변경사항에 대한 설명
- answer 컬럼 크기 변경
- 베드락 관련 코드 수정
- invokeModel.java 변경

fix: answer 컬럼 크기 수정

---

app/src/main/java/exam/master/config/InvokeModel.java

feat: add prompt engineering

---

app/src/main/java/exam/master/api/HistoryApiController.java
app/src/main/java/exam/master/config/InvokeModel.java
app/src/main/java/exam/master/service/HistoryService.java

히스토리 삭제 및 베드락 프롬프트(invokeModel) 버그
- HistoryService.java 40번 라인 확인
- InvokeModel.java 62번 라인 확인
- 관련 이슈 #59

fix: 히스토리 삭제 및 베드락 프롬프트 버그 수정

---

.idea/modules.xml
.idea/modules/app/exam-master.app.main.iml
app/build.gradle
app/src/main/java/exam/master/api/MemberApiController.java
app/src/main/java/exam/master/repository/HistoryRepository.java
app/src/main/java/exam/master/security/MemberUserDetails.java
app/src/main/java/exam/master/security/MyUserDetailsService.java
app/src/main/java/exam/master/security/SecurityConfig.java
app/src/main/java/exam/master/service/MemberService.java

스프링 시큐리티 적용
- security 패키지 추가
- 회원 업데이트 s3 업로드 추가
- 회원 삭제 s3 삭제 추가
1. security 패키지 확인
2. 멤버 업데이트 부분 확인
3. 멤버 삭제 부분 확인
- 관련 이슈 #61

feat: Spring Security 적용

---

app/src/main/java/exam/master/api/MemberApiController.java

업데이트 변경 시 json 문자열을 받을 뿐만 아니라 사진도 받아야 하기 때문에 사진 받는 부분 추가
- MemberApiController.java 77번 라인 변경

refactor: 멤버 업데이트 수정

---

app/src/main/java/exam/master/api/MemberApiController.java

비밀번호를 받을 때와 사진을 받을 때 경우
- MemberApiController.java 77번 라인 변경

refactor: 멤버 업데이트 비밀번호 코드 수정

---

app/src/main/java/exam/master/service/MemberService.java

업데이트 변경 시 새로운 사진 이름 db에 저장
- MemberService.java 69번 라인 변경

refactor: 프로필 사진 이름 변경 코드 수정

---

app/src/main/java/exam/master/api/MemberApiController.java

비밀번호 업데이트 시 암호화 된 비밀번호를 다시 암호화 해서 저장
- MemberApiController.java 77번 라인 변경

refactor: 비밀번호 업데이트 코드 수정

---

app/build.gradle
app/src/main/java/exam/master/api/socialLoginApiController.java
app/src/main/java/exam/master/domain/Member.java
app/src/main/java/exam/master/repository/MemberRepository.java
app/src/main/java/exam/master/security/CustomOAuth2UserService.java
app/src/main/java/exam/master/security/MemberUserDetails.java
app/src/main/java/exam/master/security/MyUserDetailsService.java
app/src/main/java/exam/master/security/Provider.java
app/src/main/java/exam/master/security/SecurityConfig.java
app/src/main/resources/application.yml
app/src/test/resources/application.yml

feat: 소셜 로그인

---

app/src/main/java/exam/master/config/InvokeModel.java

Bedrock Claude Sonnet 3.5 Model이 문제에 대한 더 정확한 답변과 일관된 대답을 할 수 있도록 args 수정

enhancement: prompt and top_p, top_k update

---

app/src/main/java/exam/master/security/SecurityConfig.java

로그인 성공 후 리다이렉트 경로 수정
- /social -> /home

fix: redirect 경로 수정
